export const ADD_FRIEND = 'ADD_FRIEND';
export const DELETE_FRIEND = 'DELETE_FRIEND';
export const EDIT_FRIEND = 'EDIT_FRIEND';
export const IMPORTANT_FRIEND = 'IMPORTANT_FRIEND';
export const SORT_FRIENDS = 'SORT_FRIENDS';
export const SEARCH_AND_FILTER_FRIEND = 'SEARCH_AND_FILTER_FRIEND';
export const FILTER_LIST = 'FILTER_LIST';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
